import task
import unittest

class ParseFileTest(unittest.TestCase):
    def test_a(self):
        self.assertEqual(
            task.parseFile("""
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""".strip()), 34
        )
    def test_b(self):
        self.assertEqual(
            task.parseFile("""
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
""".strip()), 9
        )

if __name__ == '__main__':
    unittest.main()